name: .NET Core 2.2
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.nuspec'
      - 'Lame.Test.Framework/**'
      - '.git*'
      - '!.git*/**.yml'
  workflow_dispatch:

jobs:
  ci:
    runs-on: windows-latest

    env:
      STORAGE: https://nuget.pkg.github.com/voicescript/index.json
      PACKAGE: Voicescript.NAudio.Lame
      
    steps:
    
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Setup .NET Core 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore packages
      run: nuget restore NAudio.Lame.sln

    - name: Build LameDLLWrap x86
      run: dotnet build ./LameDLLWrap/LameDLLWrap.csproj -a x64 -o ./LameDLLWrap/bin/x64/Debug/netstandard2.0
      
    - name: Build LameDLLWrap x64
      run: dotnet build ./LameDLLWrap/LameDLLWrap.csproj -a x86 -o ./LameDLLWrap/bin/x86/Debug/netstandard2.0
      
    - name: Pack
      run: |
        dotnet pack ./NAudio.Lame/NAudio.Lame.csproj -c Debug --output .
      env:
        VERSION: 2.1.0

    - name: Push
      run: dotnet nuget push $PACKAGE.2.1.0.nupkg --source $STORAGE --api-key ${{ secrets.GITHUB_TOKEN }}
      env:
        VERSION: 2.1.0

    

      
