name: .NET Core 2.2
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.nuspec'
      - 'Lame.Test.Framework/**'
      - '.git*'
      - '!.git*/**.yml'
  workflow_dispatch:

jobs:
  ci:
    runs-on: windows-latest

    env:
      STORAGE: https://nuget.pkg.github.com/voicescript/index.json
      PACKAGE: Voicescript.NAudio.Lame
      
    steps:

    - name: Auto Increment Semver Action
      uses: MCKanpolat/auto-semver-action@1.0.5
      id: versioning
      with:
        releaseType: patch
        incrementPerCommit: false
        github_token: ${{ secrets.TOKEN }}
    
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Setup .NET Core 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Add nuget sources
      run: |
          nuget sources add -Name "GitHub" -Source "https://nuget.pkg.github.com/voicescript/index.json" -UserName voicescript -Password ${{ secrets.TOKEN }} -StorePasswordInClearText

    - name: Restore packages
      run: nuget restore NAudio.Lame.sln

    - name: Build LameDLLWrap (Debug|x86)
      run: dotnet build LameDLLWrap -c:Debug -p:Platform=x86
      
    - name: Build LameDLLWrap (Debug|x64)
      run: dotnet build LameDLLWrap -c:Debug -p:Platform=x64
      
    - name: Build LameDLLWrap (Debug|AnyCPU)
      run: dotnet build LameDLLWrap -c:Debug -p:Platform=AnyCPU
      
    - name: Build NAudio.Lame
      run: dotnet build NAudio.Lame -c:Debug -p:Platform=AnyCPU
    
    - name: Pack
      run: |
        nuget pack ..\NAudio.Lame.nuspec -Version ${{ steps.versioning.outputs.version }} -OutputDirectory .

    - name: Push
      run: dotnet nuget push Voicescript.NAudio.Lame.${{ steps.versioning.outputs.version }}.nupkg --source https://nuget.pkg.github.com/voicescript/index.json --api-key ${{ secrets.TOKEN }}

    - name: Tag release
      shell: bash
      run: |
          git tag ${{steps.versioning.outputs.version}}
          git push origin ${{steps.versioning.outputs.version}}
          echo "Pushed tag ${{steps.versioning.outputs.version}}"

    

      
